package com.ai.soiltester.models;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class TestResult {
    private long id;
    private SensorReading reading;
    private List<Crop> recommendedCrops;
    private long timestamp;
    private String notes;
    private String location;

    public TestResult() {
        this.timestamp = System.currentTimeMillis();
    }

    public TestResult(SensorReading reading, List<Crop> recommendedCrops) {
        this.reading = reading;
        this.recommendedCrops = recommendedCrops;
        this.timestamp = System.currentTimeMillis();
    }

    // Getters
    public long getId() { return id; }
    public SensorReading getReading() { return reading; }
    public List<Crop> getRecommendedCrops() { return recommendedCrops; }
    public long getTimestamp() { return timestamp; }
    public String getNotes() { return notes; }
    public String getLocation() { return location; }

    // Setters
    public void setId(long id) { this.id = id; }
    public void setReading(SensorReading reading) { this.reading = reading; }
    public void setRecommendedCrops(List<Crop> recommendedCrops) { this.recommendedCrops = recommendedCrops; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }
    public void setNotes(String notes) { this.notes = notes; }
    public void setLocation(String location) { this.location = location; }

    // Helper methods
    public String getFormattedTimestamp() {
        SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy 'at' HH:mm", Locale.getDefault());
        return sdf.format(new Date(timestamp));
    }

    public String getShortDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy", Locale.getDefault());
        return sdf.format(new Date(timestamp));
    }

    public String getShareableText() {
        StringBuilder sb = new StringBuilder();
        sb.append("🌱 AI Soil Tester Results\n");
        sb.append("========================\n\n");
        sb.append("📊 Sensor Readings:\n");
        sb.append("💧 Soil Moisture: ").append(reading != null ? reading.getMoistureText() : "N/A").append("\n");
        sb.append("🌡️ Temperature: ").append(reading != null ? reading.getTemperatureText() : "N/A").append("\n");
        sb.append("💨 Humidity: ").append(reading != null ? reading.getHumidityText() : "N/A").append("\n\n");

        sb.append("🌾 Recommended Crops:\n");
        if (recommendedCrops != null && !recommendedCrops.isEmpty()) {
            for (int i = 0; i < recommendedCrops.size(); i++) {
                Crop crop = recommendedCrops.get(i);
                sb.append(String.format("%d. %s %s - %s (%s)\n",
                        i + 1,
                        crop.getEmoji(),
                        crop.getName(),
                        crop.getDescription(),
                        crop.getGrowingPeriodText()));
            }
        } else {
            sb.append("No recommendations available\n");
        }

        sb.append("\n📅 Date: ").append(getFormattedTimestamp()).append("\n");
        sb.append("\nGenerated by AI Soil Tester V12 Engine 🚜");

        return sb.toString();
    }

    public String getRecommendationsJson() {
        if (recommendedCrops == null) {
            return "[]";
        }

        try {
            JSONArray jsonArray = new JSONArray();
            for (Crop crop : recommendedCrops) {
                JSONObject cropObj = new JSONObject();
                cropObj.put("name", crop.getName());
                cropObj.put("emoji", crop.getEmoji());
                cropObj.put("description", crop.getDescription());
                cropObj.put("growingPeriod", crop.getGrowingPeriodText());
                cropObj.put("waterNeeds", crop.getWaterNeed());
                cropObj.put("suitabilityScore", crop.getSuitabilityScore());
                jsonArray.put(cropObj);
            }
            return jsonArray.toString();
        } catch (JSONException e) {
            return "[]";
        }
    }

    public void setRecommendationsFromJson(String json) {
        try {
            JSONArray jsonArray = new JSONArray(json);
            // Implementation would need to convert JSON back to Crop objects
            // For now, this is a placeholder
        } catch (JSONException e) {
            // Handle error
        }
    }

    @Override
    public String toString() {
        return "TestResult{" +
                "id=" + id +
                ", reading=" + reading +
                ", recommendedCrops=" + (recommendedCrops != null ? recommendedCrops.size() : 0) +
                " crops, timestamp=" + timestamp +
                '}';
    }
}